name: Prebuild Sky130
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  prebuild:
    name: Prebuild Sky130
    runs-on: ubuntu-20.04
    steps:
    - name: Get Metadata
      run: |
        echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "REPO=$(echo ${{ github.repository }} | cut -d/ -f2 | tr -d '\n')" >> $GITHUB_ENV
    - name: Checkout OpenLane
      uses: actions/checkout@v2
      with:
        repository: The-OpenROAD-Project/OpenLane
        fetch-depth: 0
    - name: Get tag name
      run: |
        SKYWATER_COMMIT=$(python3 ./dependencies/tool.py sky130 -f commit)
        OPEN_PDKS_COMMIT=$(python3 ./dependencies/tool.py open_pdks -f commit)
        echo "TAG_NAME=$SKYWATER_COMMIT-$OPEN_PDKS_COMMIT" >> $GITHUB_ENV
    - name: Check if release exists
      run: |
        echo ${{ github.token }} | gh auth login --with-token
        gh api repos/${{ github.repository }}/releases/${{ env.TAG_NAME }} || echo "GO_AHEAD=1" >> $GITHUB_ENV
    - name: Write PDK Root
      if: ${{ env.GO_AHEAD == '1' }}
      run: |
        echo "PDK_ROOT=/usr/local/pdk" >> $GITHUB_ENV
        sudo mkdir -p /usr/local/pdk
        sudo chown $USER:$USER /usr/local/pdk
    - name: Build PDK
      if: ${{ env.GO_AHEAD == '1' }}
      run: |
        make pdk
    - name: Compress PDK
      if: ${{ env.GO_AHEAD == '1' }}
      run: |
        sudo apt-get install -y pv
        tar -cf /tmp/sky130A.tar -C /usr/local/pdk/sky130A .
        pv /tmp/sky130A.tar | xz > /tmp/sky130A.tar.xz
    - name: Upload artifact
      if: ${{ env.GO_AHEAD == '1' }}
      run: |
        go get -u github.com/tcnksm/ghr
        export PATH=$PATH:$(go env GOPATH)/bin
        ghr -u ${{ env.OWNER }} -r ${{ env.REPO }} -t ${{ github.token }} ${{ env.TAG_NAME }} /tmp/sky130A.tar.xz